### ISSUE TITLE
Please add exclude sketch

### ISSUE THREAD

**Issue by sabas1080** [arduino/actions#24]
Hi

Please add commnad for exclude sketch in examples

**Comment by aentinger** [comment]
This would be indeed something we need. @per1234 can you self-assign yourself to this issue ... no immediate priority but we definitely need it sometime to have equal capability to the Travis CI actions used so far.

**Comment by per1234** [comment]
I was thinking we might be able to achieve this by instead providing the ability to specify sketch paths, which I believe is a feature @aentinger already wanted.

```
examples
|_DontTestThisOne
|_TestThisOne1
|_TestThisOne2
```
```yaml
- uses: arduino/actions/libraries/compile-examples@master
  with:
    sketch-path: '"examples/TestThisOne1" "examples/TestThisOne2"'
```
When the `sketch-path` input item is a folder, the action would recursively compile all sketches under that folder. When the `sketch-path` input is not specified, the current behavior of recursively compiling all sketches under the `examples` folder would be used.

@aentinger @sabas1080 would that be sufficient, or do you think we also need an exclude API?

**Comment by aentinger** [comment]
What I really need is to compile certain sketches only for certain boards, as we do [here](https://github.com/arduino-libraries/ArduinoIoTCloud/blob/master/.travis.yml#L80:L106). I'm not quite sure if your solution described above is solving this.

**Comment by per1234** [comment]
Yes, it would make that possible:
```yaml
strategy:
  matrix:
    fqbn: [
      "arduino:samd:mkr1000",
      "arduino:samd:mkrwifi1010",
      "arduino:samd:mkrwan1300",
      "arduino:samd:mkrwan1310",
    ]

steps:
  - uses: actions/checkout@v1
    with:
      fetch-depth: 1
  - name: compile-examples for WiFi boards
    if: matrix.fqbn == "arduino:samd.mkr1000" || matrix.fqbn == "arduino:samd.mkrwifi1010"
    uses: arduino/actions/libraries/compile-examples@master
    with:
      fqbn: ${{ matrix.fqbn }}
      libraries: ${{ env.LIBRARIES }}
      sketch-path: '"examples/ArduinoIoTCloud_LED_switch" "examples/ArduinoIoTCloud_Travis_CI" "examples/utility/Provisioning"'
  - name: compile-examples for WAN boards
    if: matrix.fqbn == "arduino:samd.mkrwan1300"
    uses: arduino/actions/libraries/compile-examples@master
    with:
      fqbn: ${{ matrix.fqbn }}
      libraries: ${{ env.LIBRARIES }}
      sketch-path: '"examples/ArduinoIoTCloud_LED_switch" "examples/ArduinoIoTCloud_Travis_CI"'
```
