### ISSUE TITLE
Rate limit error installing Taskfile

### ISSUE THREAD

**Issue by dglsparsons** [arduino/actions#65]
Hi, 

Just received the following error using the setup-taskfile GH action.

```
Run Arduino/actions/setup-taskfile@master
  with:
    version: 2.x
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_REGION: eu-west-2
    TF_WORKSPACE: staging
    GOROOT: /opt/hostedtoolcache/go/1.13.15/x64
##[error]API rate limit exceeded for 40.114.46.0. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Comment by per1234** [comment]
Hi @dglsparsons. The action has an undocumented repo-token input that allows it to be used in authenticated mode. So you can do this:
```
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
`secrets.GITHUB_TOKEN` is the automatically generated token provided by GitHub Actions:
https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

Because the input was never defined in the action's action.yml metadata file, you will get an annoying warning in your workflow:
```
##[warning]Unexpected input(s) 'repo-token', valid inputs are ['version']
```
but it will work fine and cause no problems at all.
