### ISSUE TITLE
Warnings in the logs

### ISSUE THREAD

**Issue by umbynos** [arduino/actions#83]
I'm using this action like this: 
```
- name: Install Taskfile
        uses: arduino/actions/setup-taskfile@master
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
and I'm getting this warnings:

`Warning: Unexpected input(s) 'repo-token', valid inputs are ['version']`

`Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/`

Am I missing something?
