### ISSUE TITLE
Install additional dependencies for Dockerfile

### ISSUE THREAD

**Issue by Urhengulas** [arduino/actions#91]
Hi,

I am trying to use `arduino/actions/libraries/compile-examples` for the `stm32f103C` target ([`stm32duino/Arduino_Core_STM32`](https://github.com/stm32duino/Arduino_Core_STM32). I've added that platform to my repo and specified it via the `source-path`.

```yml
on: ["push"]

jobs:
    arduino:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: arduino/actions/libraries/compile-examples@master
              with:
                  fqbn: "stm32duino:STM32F1:genericSTM32F103C"
                  platforms: |
                      - source-path: ".github/stm32duino/hardware/STM32F1"
                        name: "stm32duino:STM32F1"
                  sketch-paths: |
                      - first_launch
                  libraries: |
                      - name: MPU6050_tockn
                      - name: MS5611
                      - name: SD
                      # SPI and Wire seem to be available per default
                  enable-deltas-report: true
```

The "Run arduino/actions/libraries/compile-examples@master" step fail with:
```
Error during build: fork/exec /bin/arm-none-eabi-g++: no such file or directory
```

I assume `arm-none-eabi-g++` (available in [ubuntu repos](https://packages.ubuntu.com/focal/gcc-arm-none-eabi)) is needed for building the sketch for the stm32, which is an arm chip, but I couldn't figure out how to install this into the docker image, without forking the repo.
Is there a way?

Thanks in advance! 👋🏾
